export const HOME ='Home';
export const BOTTOM_TABS ='Bottom_tabs';
export const LOGIN = 'Login';
export const REGISTER = 'Register';
export const FORGOT_PASSWORD = 'ForgotPassword';
export const SHOPPING_CART = 'ShoppingCart'
export const MY_ORDER = 'MyOrder'
export const PROFILE = 'Profile';
export const VERIFY_REGISTER = 'VerifyRegister';
export const PRODUCT_DETAIL = 'ProductDetail'
export const PRODUCT_LIST = 'ProductList'
export const MAIN_NAV = 'Main'
export const MAKE_ORDER = 'Order'
export const ORDER_SUCCESS = 'Order_Success'
export const PURCHASE = 'Purchase'
export const ORDER_DETAIL='OrderDetail'
